Flux delete sync event
topfreegames/fluxcloud pull request #1
Opened 2020-06-29 16:25 UTC by latchmihay

Flux supports the deletion of objects, its just like a regular sync event but it has no serviceID's, the existing code was strictly checking for serviceID's and slack messages were dependent on serviceID's as well. This commit is to add no serviceID support (aka, flux delete sync event)

2020-07-02 16:44 UTC, fdpeiter commented
@latchmihay we've updated the go module for flux to the 1.19.0.
Could you please rebase and update any legacy reference?

2020-07-02 16:45 UTC, fdpeiter requested changes

2020-07-02 16:45 UTC, fdpeiter commented on pkg/exporters/slack_test.go
> +			ServiceIDs: []flux.ResourceID{},
After rebasing, I think you need to update this reference
```suggestion
			ServiceIDs: []resource.ID{},
```

2020-07-03 15:59 UTC, fdpeiter approved these changes

2020-07-03 15:59 UTC, merged

2020-07-03 16:12 UTC, fdpeiter commented
You can get the docker image with:
`docker pull quay.io/tfgco/fluxcloud`

2020-07-03 16:18 UTC, marcosnils commented on pkg/exporters/slack.go
> +	// When flux delete objects there are no ServiceIDs
I guess this function could be refactored?? IIUC we could have a single for loop to determine the slack channels?

2020-07-03 16:18 UTC, marcosnils commented on pkg/formatters/default.go
> -	if len(event.ServiceIDs) == 0 {
Interesting that this got removed and no tests had to be changed :thinking:

2020-07-06 16:46 UTC, dan-slinky-ckpd commented
@latchmihay Thanks for this PR, we've been watching and just took the opportunity to test `0.4.0` on an environment with garbage collection enabled, however fluxcloud didn't receive an event. Do you have it running successfully somewhere?

2020-07-06 16:51 UTC, dan-slinky-ckpd commented
Actually, an event with empty serviceID was received, but it didn't send a Slack message.

```
{"id":0,"serviceIDs":[],"type":"sync","startedAt":"2020-07-06T16:39:42.068985084Z","endedAt":"2020-07-06T16:39:42.068985084Z","logLevel":"info","metadata":{"commits":[{"revision":"32202e7dc85f51eae2261806059bb031162b8ada","message":"remove thing flux patch (#568)"},{"revision":"9fbe60286e2cbee2a0e26ff2f68c5331e7617a7e","message":"disable thing (#567)"}],"includes":{"other":true}}}
```

We're running `fluxcd/flux-prerelease:master-c26e9fe8`

2020-07-06 16:56 UTC, latchmihay commented
> @latchmihay Thanks for this PR, we've been watching and just took the opportunity to test `0.4.0` on an environment with garbage collection enabled, however fluxcloud didn't receive an event for sync delete. Do you have it running successfully somewhere?

No I don't, I am not sure if something has changed in Flux 1.19 in terms of the delete payload. Take a look at the tests provided and the payload on a delete event I am basing this on

2020-07-07 16:16 UTC, dan-slinky-ckpd commented
@latchmihay Ignore my comments above, your changes is correct and working as expected. The change I'm waiting for is https://github.com/fluxcd/flux/pull/3127 which will then just require a small update to the default formatter to include a list of resources. Thanks again for this contribution!

2020-07-07 16:41 UTC, fdpeiter commented
Hey @dan-slinky-ckpd! We haven't checked [this](https://github.com/fluxcd/flux/issues/2494#issuecomment-579359175) suggested change for the formatter yet, but I think that will fix this problem, right?

2020-07-07 17:16 UTC, dan-slinky-ckpd commented
@fdpeiter I'm not sure you need to make that change as the spurious list of resources issue has been resolved by https://github.com/fluxcd/flux/pull/3039. The change I'm referring to above is once https://github.com/fluxcd/flux/pull/3127 has been merged and a new flux release is published we can update the formatter to include `event.DeletedWorkloadIDs`, [for example](https://github.com/dan-slinky-ckpd/fluxcloud/commit/44ba530fb040a8beaf28a9f52b4204f0ede2e778#diff-8eabebfe03669fc383bd0098dd20fd49).

The result of that example looks like this:

<img width="530" alt="Screenshot 2020-07-07 at 16 59 22" src="https://user-images.githubusercontent.com/62966219/86817199-9bc3ce80-c07c-11ea-8f62-7266f3f5b0e9.png">

If a user does want to adapt the message to exclude the list of resources completely they should be able to override the template with `BODY_TEMPLATE`, but I've not tried that myself.

2020-07-13 18:50 UTC, fdpeiter commented
Got it, gonna keep an eye on it to add this whenever merged.